name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python-flask-hello:${{ steps.vars.outputs.tag }} , ${{ secrets.DOCKER_HUB_USERNAME }}/python-flask-hello:latest
          labels: ${{ steps.meta.outputs.labels }}
    
          
          context: .
          
          
